Extensions:
     
 ProgressBar:
  class: LiveTest\Extensions\ProgressBar
  
 Report_Echo:
  class: LiveTest\Extensions\Report
  parameter:
   writer:
    class: LiveTest\Report\Writer\Echo
    
 Report_File:
  class: LiveTest\Extensions\Report
  parameter:
   writer:
    class: LiveTest\Report\Writer\File
    parameter:
     filename: tmp.log    

 StatusBar:
  class: LiveTest\Extensions\StatusBar
  
 RunInfoHeader:
  class: LiveTest\Extensions\RunInfoHeader
