DefaultDomain: http://www.example.com

Listener:

 ProgressBar:
  class: LiveTest\Listener\Cli\ProgressBar
  
 Help:
  class: LiveTest\Listener\Cli\Help
    
 RunInfoHeader:
  class: LiveTest\Listener\Cli\InfoHeader

 Verbose:
  class: LiveTest\Listener\Verbose

 Report_Echo:
  class: LiveTest\Listener\Report
  parameter:
   logStatuses:
    - error
    - failure
   format:
    class: LiveTest\Report\Format\SimpleList
   writer:
    class: LiveTest\Report\Writer\SimpleEcho

 Report_File:
  class: LiveTest\Listener\Report
  parameter:
   logStatuses:
    - error
    - failure
   format:
    class: LiveTest\Report\Format\SimpleList
   writer:
    class: LiveTest\Report\Writer\File
    parameter:
     filename: logs/tmp.log
     
 StatusBar:
  class: LiveTest\Listener\Cli\StatusBar