DefaultDomain: http://www.example.com

Listener:

 phmLabs_Statistics:
  class: LiveTest\Packages\Website\Listener\Statistics

 Upgrade:
  class: LiveTest\Packages\Upgrade\Listener\Upgrade

 ProgressBar:
  class: LiveTest\Packages\Core\Cli\Listeners\ProgressBar
  
 Help:
  class: LiveTest\Packages\Core\Cli\Listeners\Help
    
 RunInfoHeader:
  class: LiveTest\Packages\Core\Cli\Listeners\InfoHeader

 Verbose:
  class: LiveTest\Listener\Verbose

 Report_Echo:
  class: LiveTest\Packages\Reporting\Listeners\Report
  parameter:
   logStatuses:
    - error
    - failure
   format:
    class: LiveTest\Packages\Reporting\Format\SimpleList
   writer:
    class: LiveTest\Packages\Reporting\Writer\SimpleEcho

 Report_File:
  class: LiveTest\Packages\Reporting\Listeners\Report
  parameter:
   logStatuses:
    - error
    - failure
   format:
    class: LiveTest\Packages\Reporting\Format\SimpleList
   writer:
    class: LiveTest\Packages\Reporting\Writer\File
    parameter:
     filename: logs/tmp.log
     
 StatusBar:
  class: LiveTest\Packages\Core\Cli\Listeners\StatusBar