Listener:

 ProgressBar:
  class: LiveTest\Listener\ProgressBar
  
 Help:
  class: LiveTest\Listener\Help
  
 StatusBar:
  class: LiveTest\Listener\StatusBar

Extensions:
       
 Verbose:
  class: LiveTest\Extensions\Verbose   
     
 Report_Echo:
  class: LiveTest\Extensions\Report
  parameter:
   log_statuses: 
    - error
    - failure
   format:
    class: LiveTest\Report\Format\SimpleList
   writer:
    class: LiveTest\Report\Writer\SimpleEcho
    
 Report_File:
  class: LiveTest\Extensions\Report
  parameter:
   log_statuses: 
    - error
    - failure
   format:
    class: LiveTest\Report\Format\SimpleList
   writer:
    class: LiveTest\Report\Writer\File
    parameter:
     filename: logs/tmp.log    


  
 RunInfoHeader:
  class: LiveTest\Extensions\RunInfoHeader
