Listener:

 ProgressBar:
  class: LiveTest\Listener\ProgressBar
  
 Help:
  class: LiveTest\Listener\Help
  
  
 RunInfoHeader:
  class: LiveTest\Listener\InfoHeader

 Verbose:
  class: LiveTest\Listener\Verbose

 Report_Echo:
  class: LiveTest\Listener\Report
  parameter:
   logStatuses:
    - error
    - failure
   format:
    class: LiveTest\Report\Format\SimpleList
   writer:
    class: LiveTest\Report\Writer\SimpleEcho

 Report_File:
  class: LiveTest\Listener\Report
  parameter:
   logStatuses:
    - error
    - failure
   format:
    class: LiveTest\Report\Format\SimpleList
   writer:
    class: LiveTest\Report\Writer\File
    parameter:
     filename: logs/tmp.log
     
 StatusBar:
  class: LiveTest\Listener\StatusBar