Extensions:

 Report_Html_File:
  class: LiveTest\Extensions\Report
  parameter:
   format:
    class: LiveTest\Report\Format\Html
   writer:
    class: LiveTest\Report\Writer\File
    parameter:
     filename: logs/example.html