DefaultDomain: http://www.example.com

IncludePaths:
 - /tmp
 - c:/

Listener:

 HtmlLogger:
  class: LiveTest\Listener\HtmlDocumentLog
  parameter:
   logPath: logs/

 Report_Html_File:
  class: LiveTest\Listener\Report
  parameter:
   format:
    class: LiveTest\Report\Format\Html
   writer:
    class: LiveTest\Report\Writer\File
    parameter:
     filename: logs/example.html