Extensions:

 Report_Html_File:
  class: LiveTest\Extensions\Report
  parameter:
   format:
    class: LiveTest\Report\Format\Html
   writer:
    class: LiveTest\Report\Writer\File
    parameter:
     filename: logs/example.html
     
 Report_Html_Email_Attachment:
  class: LiveTest\Extensions\Report
  parameter:
   format:
    class: LiveTest\Report\Format\Html
   writer:
    class: LiveTest\Report\Writer\EmailAttachment
    parameter:
     to: langner.nils@guj.de
     from: qm-report@guj.de
     subject: LiveTest Report - example.com - <?php echo date( 'Y-m-d' ); ?>
     attachment: report.html