Extensions:

 Report_Html_File:
  class: LiveTest\Extensions\Report
  parameter:
   format:
    class: LiveTest\Report\Format\Html
    parameter:
     css_file: http://www.phphatesme.com/LiveTest/report.css
   writer:
    class: LiveTest\Report\Writer\File
    parameter:
     filename: logs\log.html